config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get("/", {to: "pizzas#homepage", as: "whatever"})
  get("/pizzas", {to: "pizzas#index"})
  get("/pizzas/new", {to: "pizzas#new"})
  get("/pizzas/:id", {to: "pizzas#show", as: "pizza"})
  post("/pizzas", {to: "pizzas#create", as: "addpizza"})
  get("/pizzas/:id/edit", {to: "pizzas#edit"})
  patch("/pizzas/:id", {to: "pizzas#update"})

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

  def index
    @pizzas = Pizza.all
    render(:index)
  end

  def homepage
    render(:homepage)
  end
  
  def show
    @pizza = Pizza.find(params[:id])  # @pizza = Pizza.find(10)
    render(:show)
  end

  def new
    @pizza = Pizza.new
    render(:new)
  end

  def create
    name = params["pizza"]["name"]
    price = params["pizza"]["price"]
    pizzatype = params["pizza"]["pizzatype"]
    pizza = Pizza.create({name: name, price: price, pizzatype: pizzatype})
    redirect_to(pizza_path(pizza.id))
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def update
    @pizza = Pizza.find(params[:id])
    name = params["pizza"]["name"]
    price = params["pizza"]["price"]
    pizzatype = params["pizza"]["pizzatype"]
    @pizza.update({name: name, price: price, pizzatype: pizzatype})
    redirect_to pizza_path(@pizza.id)
  end
    
  

    # @article = Article.find(params[:id])
    # @article.update(title: params[:article][:title], description: params[:article][:description])
    # redirect_to article_path(@article)
  
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyPizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pizzas/edit.html.erb
<h1>Edit Your Pizza</h1>

<%=form_for @pizza do |f|%>
<%=f.label(:name) %>
<%=f.text_field(:name) %><br><br>
<%=f.label(:price) %>
<%=f.text_field(:price) %><br><br>
<%=f.label(:pizzatype) %>
<%=f.text_field(:pizzatype) %><br><br>
<%=f.submit("Edit your pizza") %>
<% end %>

app/views/pizzas/homepage.html.erb
<h1>Welcome to Happy Pizza Place</h1>

<h2><%=link_to("Click Here to See Our Menu", pizzas_path)%></h2>

app/views/pizzas/index.html.erb
<h1>Happy Pizza Menu</h2>

<ul>
  <%@pizzas.each do |pizza|%>
  <li>Name: <%=link_to(pizza.name, pizza_path(pizza.id))%>, Price: <%=pizza.price%> </li>
  <% end %>
</ul>

<h2><%= link_to("Back to the Homepage", whatever_path )%></h2>
<h2><%=link_to("Make Your Own Pizza", pizzas_new_path)%></h2>

app/views/pizzas/new.html.erb
<h1>Create Your Pizza</h1>

<%=form_for @pizza do |f|%>
<%=f.label :name %>
<%=f.text_field :name %><br><br>
<%=f.label :price %>
<%=f.text_field :price %><br><br>
<%=f.label :pizzatype %>
<%=f.text_field :pizzatype %><br><br>
<%=f.submit %>
<% end %>

app/views/pizzas/show.html.erb
<h1>Pizzas</h1>


<h2>Name: <%= @pizza.name %></h2>
<h2>Price: $<%= @pizza.price %></h2>
<h2>Ingredients: <%= @pizza.pizzatype %></h2>
<h2><%= link_to("Back to the Menu", pizzas_path)%></h2>


<img src="https://http.cat/100" alt="cat">